data:
  train_csv: "data/train.csv"
  test_dir: "data/test"
  sample_submission: "data/sample_submission.csv"
  date_col: "영업일자"
  target_col: "매출수량"
  id_col: "영업장명_메뉴명"
  min_context_days: 28
  horizon: 7
  fill_missing_dates: true
  encoding: "utf-8-sig"
  augment:
    add_noise_std: 0.0       # 표준편차; 0이면 사용 안 함
    time_shift: 0            # 입력 시퀀스 시작 위치 랜덤 시프트 범위
  time_features:
    enabled: true
    features: [day_of_week, day_of_month, month, day_of_year]
    encoding: cyclical       # cyclical|onehot|numeric (or per-feature mapping)
    normalize: true

preprocess:
  to_wide: false
  normalize: "none"           # zscore|minmax|none
  normalize_per_series: true
  eps: 1.0e-8
  clip_negative: true

train:
  device: "cuda"              # "cuda"|"cpu" 자동 선택 코드에서 처리
  epochs: 70
  early_stopping_patience: 10
  batch_size: 128
  accumulation_steps: 1
  lr_warmup_steps: 2031       # conservative warmup for unnormalized SMAPE training
  lr: 1.0e-4
  weight_decay: 1.0e-6
  grad_clip_norm: 1.0
  amp: true
  compile: false
  deterministic: false
  cuda_graphs: false         # Mutually exclusive with compile
  use_checkpoint: false      # Enable activation checkpointing to save memory at the cost of speed
  min_sigma: 1.0e-3
  min_sigma_method: "per_series_median"   # global|per_series_median aggregation for target std
  min_sigma_scale: 0.05       # floor multiplier applied to train target std
  lr_scheduler:
    type: "cosine"
    T_max: ${train.epochs}   # or explicit integer
    eta_min: 1.0e-5
  matmul_precision: "medium"
  num_workers: 4
  pin_memory: true
  persistent_workers: true
  prefetch_factor: 3
  channels_last: true
  use_loss_masking: true
  val:
    strategy: "rolling"       # "holdout"|"rolling"
    holdout_days: 35          # must be >= model.input_len + model.pred_len
    rolling_folds: 3
    rolling_step_days: 14

model:
  mode: "direct"              # "direct"|"recursive"
  input_len: 28
  pred_len: 7
  d_model: 128
  d_ff: 512
  n_layers: 2
  dropout: 0.1
  k_periods: 2
  min_period_threshold: 7  # 최소 주기 하한선
  kernel_set:
    - [3, 3]
    - [5, 5]
    - [7, 7]
  activation: "gelu"
  bottleneck_ratio: 4.0      # Bottleneck width ≈ min(in,out)/ratio (>1 contracts, <1 expands)
  use_embedding_norm: true
  id_embed_dim: 32           # Per-series identifier embedding dimension (set to 0 to disable)
  static_proj_dim: 32        # Projection size for static covariates (set to null to keep input dim)
  static_layernorm: true     # Apply LayerNorm after projecting static covariates

tuning:
  enabled: true
  n_trials: 30
  sampler: "tpe_multivariate"
  pruner: "median"
  timeout_min: null
  seed: 2025

artifacts:
  dir: "outputs/artifacts"
  model_file: "timesnet.pth"
  scaler_file: "scaler.pkl"
  schema_file: "schema.json"
  config_file: "config_used.yaml"

submission:
  out_path: "outputs/submissions/submission.csv"
  format: "date_menu"          # predictions keyed by date instead of row_key
  date_col: "영업일자"          # first column outputs business dates
